stages:
  - deploy
build_wallet:
  stage: deploy
  tags:
    - osx
  script:
    - npm install
    - git submodule update -i
    - ./update-parity.sh
    - gulp update-nodes
    - gulp wallet --platform darwin
    - ./deploy.sh
